{% set name = "apd" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apd-{{ version }}.tar.gz
  sha256: 0f59206160e08c8e7b445b505b1c901ae08c7322082ff29e925736c4f2c33ce6

build:
  noarch: python
  entry_points:
    - apd-login = apd.command:cmd_login
    - apd-logout = apd.command:cmd_logout
    - apd-cache-info = apd.command:cmd_cache_ap_info
    - apd-list-pfns = apd.command:cmd_list_pfns
    - apd-list-samples = apd.command:cmd_list_samples
    - apd-summary = apd.command:cmd_summary
    - apd-cache-pfns = apd.command:cmd_cache_pfns
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools-scm
  run:
    - python >=3.9
    - requests
    - click
    - click-log
    - rich

test:
  imports:
    - apd
  commands:
    - pip check
    - apd-cache --help
    - apd-list-pfns --help
    - apd-list-samples --help
  requires:
    - pip

about:
  home: https://pypi.org/project/apd/
  summary: Tool to access the LHCb Analysis production Data
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
