{% set name = "apd" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apd-{{ version }}.tar.gz
  sha256: 624b207d0c6bf83401f9ac07ef64a6c93c0508e765277c99bbca5acbcaca9479

build:
  number: 0
  noarch: python
  entry_points:
    - apd-cache = apd.command:cmd_cache_ap_info
    - apd-list-pfns = apd.command:cmd_list_pfns
    - apd-list-samples = apd.command:cmd_list_samples
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - beautifulsoup4
    - click
    - click-log
    - python >=3.8
    - requests
    - requests-kerberos
    - rich

test:
  imports:
    - apd
  commands:
    - pip check
    - apd-cache --help
    - apd-list-pfns --help
    - apd-list-samples --help
  requires:
    - pip

about:
  home: https://pypi.org/project/apd/
  summary: Tool to access the LHCb Analysis production Data
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
